[[commands]]
id = "browser_open"
type = "python"
script = "sh/open_browser.py"
wake_word_required = false
sounds.ru = ["ok1", "ok2", "ok3", "ok4"]

phrases.ru = [
    "открой браузер",
    "запусти браузер",
    "включи браузер",
    "браузер открой",
    "нужен браузер",
]

[[commands]]
id = "open_yandex_map"
type = "python"
script = "sh/open_yandex_map.py"
wake_word_required = false
sounds.ru = ["ok1", "ok2", "ok3", "ok4"]

phrases.ru = [
    "открой яндекс карты",
    "запусти яндекс карты",
    "включи яндекс карты",
]

[[commands]]
id = "open_addr"
type = "python"
script = "sh/open_addr.py"
wake_word_required = true
sounds.ru = ["ok1", "ok2", "ok3", "ok4"]

phrases.ru = [
    "найди адрес {addr}",
    "что по адресу {addr}",
    "что находится по адресу {addr}",
]

[commands.slots.addr]
entity = "street address"
context = ["по", "на", "адрес"]

[[commands]]
id = "open_wildberries"
type = "python"
script = "sh/open_wildberries.py"
wake_word_required = false
sounds.ru = ["ok1", "ok2", "ok3", "ok4"]

phrases.ru = [
    "открой вб",
    "запусти вб",
    "открой вы бы",
    "запусти вы бы",
    "открой вэб",
    "запусти вэб",
    "открой маркетплейс",
    "запусти маркетплейс",
    "открой маркет плейс",
    "запусти маркет плейс",
    "открой маркет",
    "запусти маркет",
]

[[commands]]
id = "browser_close"
type = "python"
script = "sh/browser_close.py"
wake_word_required = false
sounds.ru = ["ok1", "ok2", "ok3", "ok4"]
phrases.ru = [
    "закрой браузер",
    "закрой все браузеры",
    "выключи браузер",
    "убери браузер",
]
